#!/bin/sh

prefix=/usr/local
SHARE=$prefix/share/house

HAPP=orvibo

case $1 in
    remove)
        systemctl daemon-reload
        ;;
    purge)
        systemctl daemon-reload
        rm -f /etc/default/$HAPP
        ;;
esac

